/* This file is automatically generated by configure */
/* DO NOT EDIT MANUALLY */

#ifndef CONFIG_H
#define CONFIG_H


#ifndef WIIU
#define SCUMM_LITTLE_ENDIAN
#undef SCUMM_BIG_ENDIAN
//#undef SCUMM_NEED_ALIGNMENT
#define SCUMM_NEED_ALIGNMENT
#else
#undef SCUMM_LITTLE_ENDIAN
#define SCUMM_BIG_ENDIAN
#define SCUMM_NEED_ALIGNMENT
#endif
#undef USE_SDL_NET
#undef USE_ELF_LOADER
#undef DYNAMIC_MODULES
#undef USE_MT32EMU
#define USE_RGB_COLOR
#define USE_HIGHRES
#define USE_SAVEGAME_TIMESTAMP
#undef USE_SCALERS
#undef USE_HQ_SCALERS
#define USE_OGG
#define USE_VORBIS
#undef USE_TREMOR
#define USE_FLAC
#define USE_MAD
#undef USE_ALSA
#define USE_JPEG
#define USE_PNG
#define USE_THEORADEC
#define USE_FAAD

#undef USE_SEQ_MIDI
#undef USE_SNDIO
#undef USE_TIMIDITY

#define USE_ZLIB
#undef USE_MPEG2
#undef USE_LIBCURL
#undef USE_CLOUD
#undef USE_FLUIDSYNTH
#undef USE_READLINE
#undef USE_TEXT_CONSOLE_FOR_DEBUGGER
#undef USE_UNITY
#define USE_FREETYPE2
#undef USE_GLEW
#undef USE_OPENGL
#undef USE_GLES
#undef USE_GLES2
#undef USE_OPENGL_SHADERS
#undef ICONV_USES_CONST
#undef USE_ICONV
#undef USE_LINUXCD
#undef USE_NASM

#undef ENABLE_VKEYBD
#undef ENABLE_KEYMAPPER
#define USE_TRANSLATION
#define USE_DETECTLANG
#undef USE_TASKBAR
#define USE_BINK
#undef USE_UPDATES
/* #define TAINTED_BUILD */

/* Data types */
typedef unsigned char byte;
typedef unsigned int uint;
typedef unsigned char uint8;
typedef unsigned short uint16;
typedef unsigned int uint32;

typedef signed char int8;
typedef signed short int16;

typedef signed int int32;

#if defined(WIIU)
typedef signed long long int64;
typedef unsigned long long uint64;
typedef uint32 uintptr;
#else
#if defined(WIN64CROSS)
typedef signed long long int64;
typedef unsigned long long uint64;
typedef uint64 uintptr;
#else
typedef signed long int64;
typedef unsigned long uint64;
typedef uint64  uintptr;
#endif
#endif

#if defined(__APPLE__) && !defined(__ppc__)
#ifndef _UINT64
#define _UINT64
#endif
#endif

#endif /* CONFIG_H */
