# -------- Generated by configure -----------
LIBRETRO := 1
platform ?=unix
DEPS_DIR := backends/platform/sdl/deps

ifeq ($(platform), unix)
#UNIX
CXX := g++
CC := gcc
CXXFLAGS :=  -DHAVE_LIBCO=1 -fPIC -D__LIBRETRO__ -fno-exceptions -O3 -march=native -ansi -W -Wno-unused-parameter -Wno-empty-body -pedantic -Wno-long-long 
CFLAGS :=  -DHAVE_LIBCO=1 -fPIC -D__LIBRETRO__ -fno-exceptions -O3 -march=native  -W -Wno-unused-parameter -Wno-empty-body -pedantic -Wno-long-long -DWANT_ZLIB  -DFPM_DEFAULT -DFT2_BUILD_LIBRARY -DJDCT_DEFAULT=JDCT_IFAST -DSIZEOF_SIZE_T=8
LD := g++
LIBS += -lm -lrt -lpthread -lm  
#-lsndio -lvorbisfile -lvorbis  -lFLAC -lfaad -ltheoradec -logg  -lmad  -ljpeg  -lpng -lz -lfreetype
RANLIB := ranlib
STRIP := strip
AR := ar cru
AS := as
ASFLAGS := 
LITE := 1
else ifeq ($(platform), wincross64)
#WINDOWS64 cross
AR = x86_64-w64-mingw32-ar rcs
CC = x86_64-w64-mingw32-gcc
CXX = x86_64-w64-mingw32-g++ 
CXXFLAGS := -DWIN64CROSS -DHAVE_LIBCO=1 -D__LIBRETRO__ -O2 -fpermissive -DWIN32 -fno-omit-frame-pointer -D__USE_MINGW_ANSI_STDIO=0 
CFLAGS := -DWIN64CROSS  -DLIBCOFIBER -DHAVE_LIBCO=1 -D__LIBRETRO__ -O2 -DWANT_ZLIB  -DFPM_DEFAULT -DFT2_BUILD_LIBRARY -DJDCT_DEFAULT=JDCT_IFAST -DSIZEOF_SIZE_T=8 -DWIN32 -fno-omit-frame-pointer -D__USE_MINGW_ANSI_STDIO=0 
LIBS +=  -shared -static-libgcc -static-libstdc++ -lm -lmingw32 -lwinmm -lgdi32 
LD := x86_64-w64-mingw32-g++ 
RANLIB := x86_64-w64-mingw32-ranlib
STRIP := x86_64-w64-mingw32-strip
ASFLAGS := 
LITE := 1
else ifeq ($(platform), wiiu)
#WIIU
CXX := $(DEVKITPPC)/bin/powerpc-eabi-g++$(EXE_EXT)
CC := $(DEVKITPPC)/bin/powerpc-eabi-gcc$(EXE_EXT)
CXXFLAGS := -DHAVE_LIBCO=1 -D__LIBRETRO__ -fno-exceptions -Os -fpermissive
CFLAGS := -DHAVE_LIBCO=1 -D__LIBRETRO__ -fno-exceptions -Os -DWANT_ZLIB  -DFPM_DEFAULT -DFT2_BUILD_LIBRARY -DJDCT_DEFAULT=JDCT_IFAST -DSIZEOF_SIZE_T=4
WIIUDEF := -DGEKKO -mwup -mcpu=750 -meabi -mhard-float -D__POWERPC__ -D__ppc__ -DWORDS_BIGENDIAN=1 -DMSB_FIRST
WIIUDEF += -U__INT32_TYPE__ -U __UINT32_TYPE__ -D__INT32_TYPE__=int
WIIUDEF += -DHAVE_STRTOUL -DWIIU -I$(DEPS_DIR)/sdl-libretro/wiiu-deps -I$(DEPS_DIR)/libretro-common/include
CFLAGS += $(WIIUDEF)
CXXFLAGS += $(WIIUDEF)
LD := $(DEVKITPPC)/bin/powerpc-eabi-g++
RANLIB := $(DEVKITPPC)/bin/powerpc-eabi-ranlib
STRIP := $(DEVKITPPC)/bin/powerpc-eabi-strip
AR := $(DEVKITPPC)/bin/powerpc-eabi-ar$(EXE_EXT) rcs
AR_ALONE := $(DEVKITPPC)/bin/powerpc-eabi-ar$(EXE_EXT)
AS := $(DEVKITPPC)/bin/powerpc-eabi-as
ASFLAGS :=
TARGET := $(TARGET_NAME)_libretro_wiiu.a
STATIC_LINKING = 1
LITE := 1
else
#WINDOWS
AR = ar rcs
CC = gcc
CXX = g++ 
CXXFLAGS :=  -DHAVE_LIBCO=1 -fPIC -D__LIBRETRO__ -fno-exceptions -O3 -march=native -ansi -W -Wno-unused-parameter -Wno-empty-body -pedantic -Wno-long-long -fpermissive -DWIN32 -m64 
CFLAGS :=  -DHAVE_LIBCO=1 -fPIC -D__LIBRETRO__ -fno-exceptions -O3 -march=native  -W -Wno-unused-parameter -Wno-empty-body -pedantic -Wno-long-long -DWANT_ZLIB  -DFPM_DEFAULT -DFT2_BUILD_LIBRARY -DJDCT_DEFAULT=JDCT_IFAST -DSIZEOF_SIZE_T=8 -DWIN32 -m64 
LIBS += -lws2_32 -luser32 -lwinmm -ladvapi32 -lshlwapi -lwsock32 -lws2_32 -lpsapi -liphlpapi -lshell32 -luserenv -lmingw32 -shared -lgcc -lm -lmingw32
LD := g++ 
RANLIB := ranlib
STRIP := strip
ASFLAGS := 
LITE := 1
endif

WINDRES := windres
WINDRESFLAGS := 
STAGINGPATH=staging
WIN32PATH=C:/residualvm
AMIGAOSPATH=Games:ResidualVM
STATICLIBPATH=
XCODETOOLSPATH=
SPARKLEPATH=
SDLCONFIG=/home/not6/toto/sdl-libretro-master/bin/sdl-config

ABI := 

BACKEND := sdl
MODULES += backends/platform/sdl
MODULE_DIRS += 
EXEPRE := 
EXEEXT := 
NASM := 
NASMFLAGS := 
ZLIB_LIBS := #-lz
ZLIB_CFLAGS := 

prefix = /usr/local
exec_prefix = ${prefix}
bindir = ${exec_prefix}/bin
libdir = ${exec_prefix}/lib
datarootdir = ${prefix}/share
datadir = ${datarootdir}/residualvm
mandir = ${datarootdir}/man
docdir = ${datarootdir}/doc/residualvm


HAVE_GCC = 1
HAVE_GCC3 = 1
CXX_UPDATE_DEP_FLAG = -MMD -MF "$(*D)/$(DEPDIR)/$(*F).d" -MQ "$@" -MP
SDL_BACKEND = 1
#USE_SDL2 = 1
# USE_SDL_NET = 1
ifeq ($(platform), wincross64)
WIN32 = 1
else
POSIX = 1
endif
VERBOSE_BUILD = 1
# USE_ELF_LOADER = 1
# DYNAMIC_MODULES = 1
# USE_MT32EMU = 1
USE_RGB_COLOR = 1
USE_HIGHRES = 1
USE_SAVEGAME_TIMESTAMP = 1
# USE_SCALERS = 1
# USE_HQ_SCALERS = 1
USE_OGG = 1
USE_VORBIS = 1
# USE_TREMOR = 1
USE_FLAC = 1
USE_MAD = 1
#USE_ALSA = 1
USE_JPEG = 1
USE_PNG = 1
USE_THEORADEC = 1
USE_FAAD = 1
USE_ZLIB = 1
# USE_MPEG2 = 1
# USE_LIBCURL = 1
# USE_CLOUD = 1
# USE_FLUIDSYNTH = 1
USE_FREETYPE2 = 1
# USE_GLEW = 1
# USE_OPENGL = 1
# USE_GLES = 1
# USE_GLES2 = 1
# USE_OPENGL_SHADERS = 1
# ICONV_USES_CONST = 1
#USE_ICONV = 1
#USE_LINUXCD = 1
# USE_NASM = 1
# ENABLE_VKEYBD = 1
# ENABLE_KEYMAPPER = 1
# ENABLE_EVENTRECORDER = 1
USE_TRANSLATION = 1
# USE_TASKBAR = 1
USE_BINK = 1
# USE_UPDATES = 1
ENABLE_GRIM = STATIC_PLUGIN
ENABLE_MONKEY4 = 1
ENABLE_MYST3 = STATIC_PLUGIN
# ENABLE_STARK

INCLUDES += -I$(DEPS_DIR)/sdl-libretro/include/SDL -D_GNU_SOURCE=1

INCLUDES += -I$(DEPS_DIR)/libretro-common/include  
#INCLUDES += -I$(DEPS_DIR)/libretro-common/include/compat 

INCLUDES += -I$(DEPS_DIR)/libFLAC/include
INCLUDES += -I$(DEPS_DIR)/libogg/include \
	-I$(DEPS_DIR)/libvorbis/include \
	-I$(DEPS_DIR)/libvorbis/lib
INCLUDES += -I$(DEPS_DIR)/libmad
INCLUDES += -I$(DEPS_DIR)/libfaad/include -I$(DEPS_DIR)/libfaad/libfaad
INCLUDES += -I$(DEPS_DIR)/libpng
INCLUDES += -I$(DEPS_DIR)/libjpeg
INCLUDES += -I$(DEPS_DIR)/theora/include
INCLUDES += -I$(DEPS_DIR)/freetype/include

OBJS += 

DEFINES += -DSDL_BACKEND -DPOSIX -DDATA_PATH=\"${datarootdir}/residualvm\" -DPLUGIN_DIRECTORY=\"${exec_prefix}/lib/residualvm\"

ifeq ($(platform), wincross64)
LDFLAGS += -m64 --shared -static-libgcc -static-libstdc++ -Wl,--version-script=./link.T -L/usr/x86_64-w64-mingw32/lib -Wl,--export-all-symbols
else
LDFLAGS += -fPIC  -shared -Wl,--no-undefined -Wl,--version-script=./link.T
endif

port_mk = ports.mk

SAVED_CONFIGFLAGS  := --disable-opengl --disable-opengl-shaders
SAVED_LDFLAGS      := 
SAVED_CXX          := 
SAVED_CXXFLAGS     := 
SAVED_CPPFLAGS     := 
SAVED_ASFLAGS      := 
SAVED_WINDRESFLAGS := 
SAVED_SDL_CONFIG   := 
