# This file is automatically generated by configure
# DO NOT EDIT MANUALLY
# This file is being included by "Makefile.common"

ifdef ENABLE_GRIM
DEFINES += -DENABLE_GRIM=$(ENABLE_GRIM)
MODULES += engines/grim

ifdef ENABLE_MONKEY4
DEFINES += -DENABLE_MONKEY4
endif
endif

ifdef ENABLE_MYST3
DEFINES += -DENABLE_MYST3=$(ENABLE_MYST3)
MODULES += engines/myst3
endif

ifdef ENABLE_STARK
DEFINES += -DENABLE_STARK=$(ENABLE_STARK)
MODULES += engines/stark
endif
